'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { motion, useReducedMotion } from 'motion/react';
import { config } from '@fortawesome/fontawesome-svg-core';
import { faLayerGroup, faNetworkWired, faShieldHalved, faGlobe, faBars, faXmark, faCheck, faBuildingColumns, faBriefcase, faUserTie, faDisplay, faCoins, faGem, faCube, faChartSimple, faClock, faBuilding, faTableCellsLarge, faBolt, faFileLines, faEnvelope, faPlus, faMinus } from '@fortawesome/free-solid-svg-icons';
import { content } from '../lib/content';
import { Icon, Reveal, Kicker, Heading } from './shared/PageUi';
import HeroArtwork from './shared/HeroArtwork';
import RiskManagementPage from './risk-management/RiskManagementPage';
import ConnectivityPage from './connectivity/ConnectivityPage';
config.autoAddCss = false;
const serviceIcons = [faLayerGroup, faNetworkWired, faShieldHalved];
const audienceIcons = [faBuildingColumns, faBriefcase, faUserTie, faDisplay];
const marketIcons = [faCoins,faGem,faCube,faChartSimple,faClock,faBuilding,faTableCellsLarge,faBolt];
function Logo({inverse=false}) { return <img className={`brand-logo ${inverse?'inverse':''}`} src="/assets/gtc-prime-logo.webp" width="700" height="149" alt="GTC Prime"/>; }
export default function Website({language='en',page='home'}) {
 const t=content[language]; const [menu,setMenu]=useState(false); const menuButton=useRef(null); const href=(target='home',lang=language)=>`${lang==='ar'?'/ar':''}${target==='home'?'/':`/${target}/`}`;
 useEffect(()=>{ document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';setMenu(false);},[language,page]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape'){setMenu(false);menuButton.current?.focus();}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[]);
 const nav=['about','liquidity','connectivity','risk-management'];
 return <div className={language==='ar'?'font-arabic':''} dir={language==='ar'?'rtl':'ltr'} lang={language}>
  <a href="#main" className="skip-link">{t.skip}</a>
  <header className="site-header"><div className="shell header-row">
   <Link href={href()} aria-label="GTC Prime" className="logo-link"><Logo/></Link>
   <nav aria-label={language==='ar'?'القائمة الرئيسية':'Main navigation'} className="desktop-nav">{nav.map(key=><Link key={key} href={href(key)} aria-current={page===key?'page':undefined}>{t.nav[key]}</Link>)}</nav>
   <div className="header-actions"><Link className="language-control" href={href(page,language==='en'?'ar':'en')} aria-label={t.language}><Icon icon={faGlobe}/><span>{language==='en'?'العربية':'EN'}</span></Link><Link href={href('contact')} className="button button-primary header-cta">{t.talk}</Link><button ref={menuButton} onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="mobile-nav" aria-label={menu?t.close:t.menu} className="menu-toggle"><Icon icon={menu?faXmark:faBars}/></button></div>
  </div>{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label={t.menu}>{['home',...nav,'contact'].map(key=><Link key={key} href={href(key)} onClick={()=>setMenu(false)} aria-current={page===key?'page':undefined}>{t.nav[key]}</Link>)}<a href="https://mygtcportal.com/" target="_blank" rel="noopener noreferrer">{t.account}</a></nav>}</header>
  <main id="main">{page==='home'?<Home t={t} href={href}/>:page==='about'?<About t={t} href={href}/>:page==='contact'?<Contact t={t}/>:page==='risk-management'?<RiskManagementPage t={t} href={href}/>:page==='connectivity'?<ConnectivityPage t={t} href={href}/>:<Service t={t} page={page} href={href}/>}</main>
  <Footer t={t} href={href}/>
 </div>;
}
function Home({t,href}) { return <>
 <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><Kicker>{t.hero.eyebrow}</Kicker><h1 className="text-display mt-7">{t.hero.line1}<br/><span className="text-primary">{t.hero.line2}</span></h1><p className="hero-description">{t.hero.description}</p><div className="button-row"><Link href={href('contact')} className="button button-primary">{t.talk}</Link><a href="#solutions" className="button button-outline">{t.explore}</a></div><p className="hero-foot"><span className="mini-rule"/>{t.hero.foot}</p></div><HeroArtwork alt={t.hero.art} captionLeft="01 / 03" captionRight={t.services.map(s=>s.title).join(' · ')}/></div></section>
 <div className="platform-strip"><div className="shell platform-row"><span>{t.platforms}</span><div>MetaTrader <b>4</b></div><div>MetaTrader <b>5</b></div><div className="ctrader">cTrader</div><span className="strip-end">{t.hero.foot}</span></div></div>
 <section className="section shell" id="solutions"><Reveal className="section-top"><div><Kicker>{t.labels.solutions}</Kicker><Heading>{t.intro.title}</Heading></div><p className="section-intro">{t.intro.description}</p></Reveal><div className="solutions-grid">{t.services.map((s,i)=><Reveal key={s.slug} delay={i*.08} className="service-card"><div className="card-top"><span className="icon-tile"><Icon icon={serviceIcons[i]}/></span><span className="card-number">0{i+1}</span></div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.features.map(f=><li key={f}><Icon icon={faCheck}/>{f}</li>)}</ul><Link href={href(s.slug)} className="text-link" aria-label={`${t.discover}: ${s.title}`}>{t.discover}<span className="link-line"/></Link></Reveal>)}</div></section>
 <Audience t={t} href={href}/><Technology t={t} href={href}/><Markets t={t} href={href}/>
 <section className="section shell"><Reveal className="section-top"><div><Kicker>{t.labels.why}</Kicker><Heading>{t.whyTitle}</Heading></div><Link href={href('about')} className="text-link">{t.nav.about}<span className="link-line"/></Link></Reveal><div className="benefits">{t.benefits.map(([title,desc],i)=><Reveal key={title} delay={i*.08}><span className="benefit-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></Reveal>)}</div></section>
 <Brochure t={t}/><CTA t={t} href={href}/>
 </>; }
function Audience({t,href}) { const [active,setActive]=useState(0);return <section className="audience-section section"><div className="shell audience-grid"><Reveal><Kicker>{t.labels.who}</Kicker><Heading>{t.audienceTitle}</Heading><p className="section-intro mt-6">{t.audienceText}</p><Link href={href('contact')} className="text-link mt-8">{t.talk}<span className="link-line"/></Link></Reveal><Reveal className="audience-list">{t.audiences.map(([title,desc],i)=><div className={`audience-item ${active===i?'active':''}`} key={title}><button onClick={()=>setActive(active===i?-1:i)} aria-expanded={active===i} aria-controls={`audience-${i}`}><span className="audience-icon"><Icon icon={audienceIcons[i]}/></span><span>{title}</span><Icon icon={active===i?faMinus:faPlus}/></button>{active===i&&<motion.p id={`audience-${i}`} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}>{desc}</motion.p>}</div>)}</Reveal></div></section>;}
function Technology({t,href}) { return <section className="section shell"><div className="technology-grid"><Reveal className="technology-panel"><p className="panel-label">{t.ecosystem}</p><div className="network-diagram"><div className="network-core"><Logo/></div><div className="network-partners">{['MetaQuotes','PrimeXM','FXCubic','Your Bourse'].map(n=><div key={n}>{n}</div>)}</div></div><div className="platform-tags"><span>MT4</span><span>MT5</span><span>cTrader</span></div></Reveal><Reveal className="technology-copy"><Kicker>{t.labels.tech}</Kicker><Heading>{t.techTitle}</Heading><p className="section-intro mt-6">{t.techText}</p><Link href={href('connectivity')} className="button button-primary mt-8">{t.techLink}</Link></Reveal></div></section>;}
function Markets({t,href}) {const [selected,setSelected]=useState(0);const refs=useRef([]);function keyChange(e,i){let n=i;if(e.key==='ArrowRight')n=(i+1)%8;else if(e.key==='ArrowLeft')n=(i+7)%8;else if(e.key==='Home')n=0;else if(e.key==='End')n=7;else return;e.preventDefault();setSelected(n);refs.current[n]?.focus();}return <section className="markets-section section"><div className="shell"><Reveal className="section-top"><div><Kicker>{t.labels.markets}</Kicker><Heading>{t.marketTitle}</Heading></div><p className="section-intro">{t.marketText}</p></Reveal><Reveal><div className="market-tabs" role="tablist" aria-label={t.marketPrompt}>{t.markets.map(([label],i)=><button key={label} ref={el=>{refs.current[i]=el}} role="tab" id={`market-tab-${i}`} aria-controls="market-panel" aria-selected={selected===i} tabIndex={selected===i?0:-1} onKeyDown={e=>keyChange(e,i)} onClick={()=>setSelected(i)} className={selected===i?'selected':''}><Icon icon={marketIcons[i]}/><span>{label}</span></button>)}</div><div className="market-panel" id="market-panel" role="tabpanel" aria-labelledby={`market-tab-${selected}`} tabIndex={0}><div className="market-symbol"><Icon icon={marketIcons[selected]}/></div><div><h3>{t.markets[selected][0]}</h3><p>{t.markets[selected][1]}</p></div><Link href={href('contact')} className="text-link">{t.marketDetails}<span className="link-line"/></Link></div></Reveal></div></section>;}
function Brochure({t}) {return <section className="shell brochure-wrap"><Reveal className="brochure"><div className="brochure-icon"><Icon icon={faFileLines}/></div><div><Kicker>{t.labels.brochure}</Kicker><h3>{t.brochureTitle}</h3><p>{t.brochureText}</p></div><a className="button button-outline" href="https://gtcprime.com/wp-content/uploads/2023/04/GTC-Prime-Profile-.pdf" target="_blank" rel="noopener noreferrer"><Icon icon={faFileLines}/>{t.download}</a></Reveal></section>;}
function CTA({t,href}) { return <section className="section shell"><Reveal className="cta-block"><div><Kicker light>{t.labels.contact}</Kicker><Heading>{t.ctaTitle}</Heading><p>{t.ctaText}</p></div><Link href={href('contact')} className="button button-white">{t.talk}</Link><span className="cta-decoration" aria-hidden="true"/></Reveal></section>;}
function About({t,href}) {return <><section className="inner-hero shell"><Kicker>{t.labels.about}</Kicker><h1 className="whitespace-pre-line">{t.aboutTitle}</h1><div className="about-intro"><p>{t.aboutText}</p><div className="about-statement"><span>GTC PRIME</span><p>{t.footer.line}</p></div></div></section><section className="section section-border shell"><Reveal className="section-top"><Heading>{t.aboutSub}</Heading><p className="section-intro">{t.aboutMore}</p></Reveal><div className="benefits">{t.benefits.map(([title,desc],i)=><Reveal key={title} delay={i*.08}><span className="benefit-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></Reveal>)}</div></section><Audience t={t} href={href}/><Technology t={t} href={href}/><CTA t={t} href={href}/></>;}
function Service({t,page,href}) {const index=t.services.findIndex(s=>s.slug===page);const s=t.services[index];if(!s)return null;return <><section className="inner-hero shell service-hero"><div><Kicker>{s.title}</Kicker><h1 className="whitespace-pre-line">{s.detailTitle}</h1><p className="inner-description">{s.detail}</p><Link href={href('contact')} className="button button-primary mt-8">{t.talk}</Link></div><div className="service-emblem"><span className="emblem-number">0{index+1}</span><Icon icon={serviceIcons[index]}/><span>{s.title}</span></div></section><section className="section section-border shell"><div className="service-details">{s.sections.map(([title,desc],i)=><Reveal key={title} delay={i*.1}><span className="benefit-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></Reveal>)}</div></section>{page==='liquidity'?<Markets t={t} href={href}/>:page==='connectivity'?<Technology t={t} href={href}/>:<Audience t={t} href={href}/>}<Brochure t={t}/><CTA t={t} href={href}/></>;}
function Contact({t}) {const [draft,setDraft]=useState('');const [copied,setCopied]=useState(false);const [copyFailed,setCopyFailed]=useState(false);function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const body=`Name: ${f.get('name')}\nEmail: ${f.get('email')}\nCompany: ${f.get('company')}\nSolution: ${f.get('interest')}\n\n${f.get('message')}`;setDraft(body);window.location.href=`mailto:support@gtcprime.com?subject=${encodeURIComponent('GTC Prime — '+f.get('interest'))}&body=${encodeURIComponent(body)}`;}return <section className="section shell contact-grid"><div className="contact-intro"><Kicker>{t.labels.contact}</Kicker><h1 className="whitespace-pre-line">{t.ctaTitle}</h1><p className="section-intro mt-6">{t.ctaText}</p><div className="contact-email"><Icon icon={faEnvelope}/><p>{t.form.emailDirect}<a href="mailto:support@gtcprime.com">support@gtcprime.com</a></p></div></div><div className="contact-form"><h2 className="text-h3">{t.form.title}</h2><form onSubmit={submit}><div className="form-grid"><label>{t.form.name} *<input name="name" autoComplete="name" required maxLength={100}/></label><label>{t.form.email} *<input type="email" name="email" autoComplete="email" required maxLength={150}/></label><label>{t.form.company} *<input name="company" autoComplete="organization" required maxLength={150}/></label><label>{t.form.interest} *<select name="interest" required defaultValue=""><option value="" disabled>{t.form.select}</option>{t.services.map(s=><option key={s.slug}>{s.title}</option>)}</select></label><label className="full-width">{t.form.message} *<textarea name="message" rows={5} required maxLength={2000} placeholder={t.form.placeholder}/></label></div><p className="form-note">{t.form.privacy}</p><button className="button button-primary w-full" type="submit">{t.form.submit}</button><p className="form-note">{t.form.note}</p></form>{draft&&<div className="draft-state" role="status"><h3 className="text-h4">{t.form.successTitle}</h3><p>{t.form.ready}</p><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopied(true);}catch{setCopyFailed(true);}}}>{copied?t.form.copied:t.form.copy}</button>{copyFailed&&<textarea aria-label={t.form.copy} readOnly value={draft} onFocus={e=>e.target.select()}/>}</div>}</div></section>;}
function Footer({t,href}) {return <footer className="site-footer"><div className="shell"><div className="footer-top"><div><Link href={href()} aria-label="GTC Prime"><Logo/></Link><p>{t.footer.line}</p></div><div><h4>{t.footer.company}</h4><Link href={href('about')}>{t.nav.about}</Link><Link href={href('contact')}>{t.nav.contact}</Link><a href="https://mygtcportal.com/" target="_blank" rel="noopener noreferrer">{t.account}</a></div><div><h4>{t.footer.solutions}</h4>{t.services.map(s=><Link key={s.slug} href={href(s.slug)}>{s.title}</Link>)}</div><div><h4>{t.footer.contact}</h4><a href="mailto:support@gtcprime.com">support@gtcprime.com</a><span className="footer-accent"/></div></div><div className="legal-copy"><h5>{t.footer.riskTitle}</h5><p>{t.footer.risk}</p><p>{t.footer.legal}</p><p>{t.footer.restriction}</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} GTC Prime. {t.footer.rights}</span><span>GTC PRIME</span></div></div></footer>;}
